############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "À propos"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Événements 2026"
hasChildren = true

  [[main]]
  parent = "Événements 2026"
  name = "St-Laurent (2 jours)"
  url = "raid_stlaurent_2026/"
  weight = 1

  [[main]]
  parent = "Événements 2026"
  name = "St-Laurent (7h)"
  url = "raid_stlaurent8h_2026/"
  weight = 2


[[main]]
weight = 4
name = "Événements passés"
hasChildren = true

  [[main]]
  parent = "Événements passés"
  name = "St-Laurent (2 jours)- 2025"
  url = "raid_stlaurent_2025/"
  weight = 1

  [[main]]
  parent = "Événements passés"
  name = "St-Laurent (5h)- 2025"
  url = "raid_stlaurent5h_2025/"
  weight = 2

  [[main]]
  parent = "Événements passés"
  name = "St-Laurent (8h)- 2025"
  url = "raid_stlaurent8h_2025/"
  weight = 3

  [[main]]
  parent = "Événements passés"
  name = "Jackalope (2 jours) - 2024"
  url = "jackalope_2024/"
  weight = 4

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 6h - 2024"
  url = "jackalope6h_2024/"
  weight = 5

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 4h - 2024"
  url = "jackalope4h_2024/"
  weight = 6

  [[main]]
  parent = "Événements passés"
  name = "Jackalope (2 jours) - 2023"
  url = "jackalope_2023/"
  weight = 7

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 6h - 2023"
  url = "jackalope6h_2023/"
  weight = 8

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 4h - 2022"
  url = "jackalope_short/"
  weight = 9

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 12h - 2022"
  url = "jackalope_long/"
  weight = 10

[[main]]
name = "Partenaires"
url = "partenaires/"
weight = 5

[[main]]
name = "Récits de course"
url = "blog/"
weight = 6

[[main]]
name = "FAQ"
url = "faq/"
weight = 7

[[main]]
name = "Contact"
url = "contact/"
weight = 8


# footer menu
[[footer]]
name = "À propos"
url = "about/"
weight = 1

[[footer]]
name = "St-Laurent (2 jours)"
url = "raid_stlaurent_2026/"
weight = 2


[[footer]]
name = "St-Laurent (7h)"
url = "raid_stlaurent8h_2026/"
weight = 3


[[footer]]
name = "Contact"
url = "contact/"
weight = 4
