############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "À propos"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Événements"
hasChildren = true

  [[main]]
  parent = "Événements"
  name = "Défi Jackalope 4h"
  url = "jackalope_short/"
  weight = 1

  [[main]]
  parent = "Événements"
  name = "Défi Jackalope 12h"
  url = "jackalope_long/"
  weight = 2

[[main]]
name = "Partenaires"
url = "partenaires/"
weight = 4


[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "À propos"
url = "about/"
weight = 1

[[footer]]
name = "Défi Jackalope 4h"
url = "jackalope_short/"
weight = 2


[[footer]]
name = "Défi jackalope 12h"
url = "jackalope_long/"
weight = 3

#[[footer]]
#name = "Service"
#url = "service/"
#weight = 4

#[[footer]]
#name = "Tarification"
#url = "pricing/"
#weight = 5

#[[footer]]
#name = "Questions fréquentes"
#url = "faq/"
#weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 4
