############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "À propos"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Événements"
hasChildren = true

  [[main]]
  parent = "Événements"
  name = "Défi Jackalope 2023"
  url = "jackalope_2023/"
  weight = 1

  [[main]]
  parent = "Événements"
  name = "Défi Jackalope 6h 2023"
  url = "jackalope6h_2023/"
  weight = 2

[[main]]
weight = 3
name = "Événements passés"
hasChildren = true

  [[main]]
  parent = "Événements passés"
  name = "Défi Jackalope 2022 - 4h"
  url = "jackalope_short/"
  weight = 1

  [[main]]
  parent = "Événements passés"
  name = "Défi Jackalope 2022 - 12h"
  url = "jackalope_long/"
  weight = 2

[[main]]
name = "Partenaires"
url = "partenaires/"
weight = 4

[[main]]
name = "Récits de course"
url = "blog/"
weight = 5

[[main]]
name = "FAQ"
url = "faq/"
weight = 6

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "À propos"
url = "about/"
weight = 1

[[footer]]
name = "Défi Jackalope"
url = "jackalope_2023/"
weight = 2


[[footer]]
name = "Défi Découverte"
url = "decouverte_2023/"
weight = 3

#[[footer]]
#name = "Service"
#url = "service/"
#weight = 4

#[[footer]]
#name = "Tarification"
#url = "pricing/"
#weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 4
