############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "À propos"
url = "about/"
weight = 2

#[[main]]
#name = "Événementsaa 2024"
#url = "project/"
#weight = 3

[[main]]
weight = 3
name = "Événements 2024"
hasChildren = true

  [[main]]
  parent = "Événements 2024"
  name = "Jackalope (2 jours)"
  url = "jackalope_2024/"
  weight = 1

  [[main]]
  parent = "Événements 2024"
  name = "Jackalope 6h"
  url = "jackalope6h_2024/"
  weight = 2

  [[main]]
  parent = "Événements 2024"
  name = "Jackalope 4h"
  url = "jackalope4h_2024/"
  weight = 3

[[main]]
weight = 3
name = "Événements passés"
hasChildren = true

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 2 jours - 2023"
  url = "jackalope_2023/"
  weight = 1

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 6h - 2023"
  url = "jackalope6h_2023/"
  weight = 2

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 4h - 2022"
  url = "jackalope_short/"
  weight = 3

  [[main]]
  parent = "Événements passés"
  name = "Jackalope 12h - 2022"
  url = "jackalope_long/"
  weight = 4

[[main]]
name = "Partenaires"
url = "partenaires/"
weight = 4

[[main]]
name = "Récits de course"
url = "blog/"
weight = 5

[[main]]
name = "FAQ"
url = "faq/"
weight = 6

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "À propos"
url = "about/"
weight = 1

[[footer]]
name = "Jackalope 2024"
url = "jackalope_2024/"
weight = 2


#[[footer]]
#name = "Défi Jackalope 6h"
#url = "jackalope6h_2023/"
#weight = 3

#[[footer]]
#name = "Service"
#url = "service/"
#weight = 4

#[[footer]]
#name = "Tarification"
#url = "pricing/"
#weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 4
